### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by veyndan** [torgard/DevCalc#11]
What are your thoughts on updating the UI. To me it seems a bit archaic and could do with some prettying up. Also the calculator buttons gives me the illusion of dots between the buttons i.e. the [grid illusion](https://en.wikipedia.org/wiki/Grid_illusion). I have an idea for a better UI which I could implement, but I don't want to do it if you are really attached to the current design.

**Comment by aksel** [comment]
It is indeed archaic and stuff, but I think that's what makes it neat. Simple, no bullshit.

But I'm open to suggestions.

Yes, the grid illusion is pretty annoying.
One way to work around it is by decreasing the space between the buttons, but in order for it to work, the spacing has to be so small that it looks kind of ugly.

So yeah, open to suggestions.

**Comment by veyndan** [comment]
Here's an idea below.

![screenshot_20161116-175004](https://cloud.githubusercontent.com/assets/6900601/20358855/58913e28-ac25-11e6-9940-08e65acd2866.png)

I'm not happy with the colors, but you can see the general layout.

**Comment by aksel** [comment]
That's beautiful! Really nice-looking

**Comment by veyndan** [comment]
Thanks! I'll make a PR later if you're happy with it, though I'll make the colors work together a bit better beforehand.

**Comment by veyndan** [comment]
Closed by #12
