### ISSUE TITLE
Calculator.java.orig

### ISSUE THREAD

**Issue by veyndan** [torgard/DevCalc#5]
I noticed that in the most recent commit you added a file `Calculator.java.orig`. What is the reason for this file? It seems like the old version of `Calculator.java`, in which case, why not rely on Git and checkout previous commits instead which is a core feature of Git.

**Comment by aksel** [comment]
Didn't notice it.
There were merge conflicts with the latest pull request, where you converted mInput to primitive.

I initially used Git Extensions to resolve them, but had some trouble. Seems that .orig was generated in the process.

I'll delete it.

**Comment by veyndan** [comment]
Oh right, that makes sense! And thanks!

**Comment by aksel** [comment]
And thanks to you, too!
Your pull requests are greatly appreciated

**Comment by veyndan** [comment]
No problem! 

Btw, instead of Git Extensions, you can use Android Studio's built in functionality which I am pretty pleased with. I mainly only use it for merging and diffing though and use the terminal for everything else. If you haven't used it before, I'll happily tell you how to get it. If you have used it then there is no point in me typing out the steps.

**Comment by aksel** [comment]
I'm usually on my laptop, which is very old. I think it's from around 2007.

Point is, it can't handle Android Studio. So I usually use the terminal or Git Extensions

On my desktop, I do use Android Studio's built in functionality

**Comment by veyndan** [comment]
Makes sense, just thought I'd let you know in case you hadn't heard about it.
